Add resource monitor collector
morganstanley/testplan pull request #1031
Opened 2023-12-11 06:30 UTC by yuxuan-ms

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2023-12-13 07:02 UTC, Pyifan requested changes

2023-12-13 07:02 UTC, Pyifan commented on testplan/common/report/resource.py
> +        self.logger.addHandler(fhandler)
if we don't intent to use TESTPLAN logger, maybe do not inherit from Loggable

2023-12-13 07:22 UTC, Pyifan requested changes

2023-12-13 07:22 UTC, Pyifan commented on testplan/common/report/resource.py
> +        shared_dict["collector_port"] = self.collector_port
do we need both address and collector_port?

2023-12-13 07:40 UTC, Pyifan commented on testplan/common/report/event.py
move event.py and resource.py to testplan/monitor

2023-12-19 04:10 UTC, Pyifan requested changes

2023-12-19 04:10 UTC, Pyifan commented on testplan/monitor/resource.py
> +        disk_path: str = "/",
keep disk_path, and default to pwd() (since client does not have a runpath, otherwise runpath will be a better option)

remove all other parameters

2023-12-19 04:10 UTC, Pyifan commented on testplan/monitor/resource.py
> +        self.disk_size = psutil.disk_usage(disk_path).total
move disk_size to enrich_metadata

2023-12-19 08:26 UTC, Pyifan requested changes

2023-12-19 08:26 UTC, Pyifan commented on testplan/monitor/resource.py
> +        self.parent_pid: int = os.getpid()
not used

2023-12-21 07:13 UTC, Pyifan approved these changes

2023-12-21 07:17 UTC, Pyifan commented
If we start a process pool, we will have multiple client on local server?
And we need a test.

2023-12-21 07:27 UTC, zhenyu-ms commented on testplan/monitor/resource.py
> +        self._zmq_context: Optional[zmq.sugar.context.Context] = None
```suggestion
        self._zmq_context: Optional[zmq.Context] = None
```

2023-12-21 07:41 UTC, zhenyu-ms commented on testplan/monitor/resource.py
> +        self._file_handler: Dict[
maybe replace nested dict with namedtuple?

2023-12-21 09:05 UTC, zhenyu-ms commented on testplan/monitor/resource.py
> +                memory_used=psutil.virtual_memory().used,
maybe (total - available)

2024-01-12 01:37 UTC, Pyifan approved these changes

2024-01-12 02:33 UTC, merged