Fix/reload report
morganstanley/testplan pull request #1062
Opened 2024-03-12 10:32 UTC by zhenyu-ms

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [x] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2024-03-14 08:57 UTC, kn-ms requested changes
Can you fill the template. It is not clear what this pr is fixing, I feel that this also can have an newwfragment

2024-03-14 08:57 UTC, kn-ms commented on testplan/common/report/base.py
> +        del self._index[uid]
if you rebuild the whole index, this is pointless

2024-03-14 08:57 UTC, kn-ms commented on tests/functional/testplan/runnable/interactive/test_reloader.py
I guess the idea to having the before after state in a single file is based on the need to easily see the differences when one working with them.

I think clubbing them together in a single file does not serve that as if they would be in two different I could easily diff them, or just open side by side and it would be visual. Also the assertions are anyway in a different file so you need to open more than one when working on this testcase.

Having them two separate .py file has some added value:
  - we can diff or see the diff between before after easily
  - you do not need the split logic, which is ugly and do not document that well the secret that you need exactly 80 # as separator
  - you will get black formatting so the code in it conforms the rest.
  - if we refactoring something used in these examples they will be automatically refactored as well

2024-03-14 08:57 UTC, kn-ms commented on tests/functional/testplan/runnable/interactive/test_reloader.py
> +            f.writelines(curr_lines)
This may leak a file descriptor if writelines throwing an exception. See my other comment and just use simple copy over.

2024-03-19 10:22 UTC, kn-ms commented on tests/functional/testplan/runnable/interactive/test_reloader.py
> +def load_case_paths(case_num):
this actually not loading anything, how about  `get_testcase_paths` ?

2024-03-19 10:27 UTC, kn-ms submitted a review, later dismissed

2024-03-20 04:58 UTC, Pyifan requested changes

2024-03-20 04:58 UTC, Pyifan commented on testplan/runnable/interactive/base.py
> -                            ] = suite[case.uid]
I think this is where the original problem is right? that we assume case of a particular uid is still at the same index?

2024-03-20 04:58 UTC, Pyifan commented on testplan/runnable/interactive/base.py
> -                            ] = suite[case.uid]
Can we just fix this bit?

2024-03-20 04:58 UTC, Pyifan commented on testplan/runnable/interactive/base.py
> +                curr.status_override = prev.status_override
Copying selected entries from prev to curr isn't very bulletproof, how do we know these are everything we need to copy? or what if we add new fields to report, we will forget to come back here to update.

2024-04-29 02:36 UTC, Pyifan approved these changes

2024-04-29 02:39 UTC, merged