Make multitest env start/stop failure more explicit for xfail.
morganstanley/testplan pull request #1075
Opened 2024-04-24 04:18 UTC by yuxuan-ms

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2024-05-07 03:41 UTC, zhenyu-ms commented on tests/functional/testplan/testing/multitest/test_pre_post_steps.py
> +                                uid="check_func_1",
i think we'd better add "category" back

2024-05-07 03:41 UTC, zhenyu-ms commented on testplan/report/testing/base.py
> +            if child.category == ReportCategories.SYNTHESIZED:
will this affect filtering by tags?

2024-05-08 04:03 UTC, zhenyu-ms commented on testplan/testing/base.py
> +    def _add_resource_report(self, name):
if no resources && no start/stop related hook, skip synthesize this suite report?

2024-05-08 05:33 UTC, Pyifan requested changes

2024-05-08 05:33 UTC, Pyifan commented on testplan/testing/base.py
> +    def _run_resource_hook(self, hook: Callable, report_name: str) -> None:
suggest rename parameter report_name --> suite_name

2024-05-08 05:33 UTC, Pyifan commented on testplan/testing/base.py
> +            self._add_resource_report, name=ResourceHooks.environment_start
suggest that we add environment_start/stop testsuite in _run_resource_hook when not present --> then we have less steps and helps readability

2024-05-08 05:33 UTC, Pyifan commented on testplan/testing/base.py
> +    def _start_resource(self) -> TestCaseReport:
can we do a

if not self.resources: return

here?

2024-05-08 05:33 UTC, Pyifan commented on testplan/testing/base.py
> +    def _dry_run_start_resource(self) -> TestCaseReport:
same here, if self.resources is empty, return

2024-05-31 10:52 UTC, closed without merging