Add Driver connection
morganstanley/testplan pull request #1118
Opened 2024-07-22 05:16 UTC by dteo00

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/connection_info.py
> +                self.service = driver_connection_info.service.upper()
if first node is `HTTP`, pending node is `FTP`, to raise?

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/base.py
> +                            new_connection = connection(conn_info)
i don't quite like this idea here, suggest associate those classes through methods, maybe `new_connection = conn_info.promote_to_connection()`

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/base.py
> +            except Exception as err:
exception type too general, pls narrow down

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/base.py
> +                self.logger.debug(
use `info` level instead?

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/base.py
> +                    f"Error getting metadata for driver {driver}: {err}"
```suggestion
                    "Error getting metadata for driver %s: %s", driver, err
```

2024-07-23 09:25 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/base.py
> +    def __init__(self, driver_connection_info: BaseConnectionInfo):
this constructor wasn't quite self-explaining at first sight, suggest having a attribute-initialising-only one and having a new class method for concrete logic needed

2024-07-23 09:57 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/base.py
> +    def connection(self):
suggest a name like `connection_rep`, plain `connection` is kind of confusing

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/connection_info.py
> +                self.drivers_listening[driver_name].append(port)
i suppose port will be the same for all these drivers?

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/get_connection.py
we need another mod name, or maybe merge it into another mod

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/base.py
> +    drivers_listening: "defaultdict[List]"
`listening` tends to be meaningless for file-based conn, may have different attr for network & file instead of sharing the same in the base class

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/entries/base.py
> +        super(FlowChart, self).__init__(description=description)
```suggestion
        super().__init__(description=description)
```

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/base.py
> +    def identifier(self):
do we still need this attr?

2024-08-01 10:27 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/base.py
> +    identifier: Union[int, str, ContextValue]
if `connection_rep` implemented for different Connection Info type, i don't think we still need this identifier

2024-08-01 16:12 UTC, Pyifan requested changes

2024-08-01 16:12 UTC, Pyifan commented on testplan/testing/multitest/driver/connection/base.py
> +class BaseConnectionInfo:
I suggest that we rename this series of class to ConnectionExtractor - BaseConnectionExtractor, PortConnectionExtractor, FileConnectionExtractor etc.

Add a new ConfigOption connection_extractors to driver class, which takes a list of extractor objects. And a reasonable default for stock drivers.

The BaseConnectionExtractor is just going to read host/port information from driver's properties.
PortConnectionExtractor will check tcp/udp port etc.
And FileConnectionExtractor will check open fd.
(I think you are already doing above).

Let's decommission all driver metadata related feature from our code.

Create DriverConnections class to aggregate all connections of drivers in this environment.
(I see currently we are only using a list for that, I would prefer to have a proper class with necessary methods)

2024-08-01 16:14 UTC, Pyifan commented on testplan/runnable/base.py
>              ConfigOption("driver_info", default=False): bool,
let this one driver_info cmdline arg to rule them all

2024-08-01 16:15 UTC, Pyifan commented on testplan/testing/base.py
> +        connections: List[BaseDriverConnection] = []
Here is where I think a DriverConnections class is needed to aggregate the result of calling each drivers connection extractor.

2024-08-01 16:16 UTC, Pyifan commented on testplan/testing/multitest/driver/base.py
> +    DIRECTION = None
I think these needs to be encapsulated into ConnectionExtractor

2024-08-01 16:18 UTC, Pyifan commented on testplan/testing/multitest/driver/base.py
> +    def local_host(self):
can we just call these host and port?
maybe don't need this dummy property in base class.
only add these properties to drivers who uses a BaseConnectionExtractor?

2024-08-05 09:40 UTC, zhenyu-ms commented on testplan/testing/multitest/driver/connection/connection_extractor.py
> +class PortConnectionExtractor(BaseConnectionExtractor):
this extractor only works when driver has a subprocess, maybe change the class name to inform the user?

2024-08-06 07:40 UTC, Pyifan requested changes

2024-08-06 07:40 UTC, Pyifan commented on testplan/testing/multitest/driver/connection/base.py
> +    name: str  # name of the connection
is name more a type of the connection?

2024-08-06 07:40 UTC, Pyifan commented on testplan/testing/multitest/driver/connection/base.py
> +    LISTENING = "listening"
Do we need BIDIRECTIONAL = "bidirectional" for file/shm type of connection?

2024-08-07 04:01 UTC, Pyifan approved these changes

2024-08-07 04:04 UTC, merged