Doc/update interactive reload limitation
morganstanley/testplan pull request #1127
Opened 2024-08-23 10:31 UTC by zhenyu-ms

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2024-08-23 10:32 UTC, yuxuan-ms submitted a review, later dismissed

2024-08-27 05:55 UTC, Pyifan requested changes

2024-08-27 05:55 UTC, Pyifan commented on doc/en/interactive.rst
> +  works purely on static analysis, which means it is completely ignorant of any
let's explain in a bit more detail how module finder find the dependency of the module from import statement:
- absolute import if the module path is accessible from the root (pwd)? (e.g import a.b.c, and if a is under root syspath)
- relative import if the module path is reachable from current module (e.g import ..x.y, if we can traverse to x from current module)

run this through co-pilot for refinement

2024-09-02 09:11 UTC, Pyifan approved these changes

2024-09-03 04:02 UTC, merged