Force to execute testcases sequentially in a test suite
morganstanley/testplan pull request #593
Opened 2021-03-10 10:05 UTC by raoyitao

* An attribute "strict_order" is added into test suite and testcases
  in this suite must run sequentially one by one and parallel feature
  such as execution group is disabled in batch mode.
* A test suite with "strict_order" ignores `test_sorter` configured for
  Test runner, and `test_filter` config does not take effect unless all
  of the testcases in suite been filtered out.
* If "strict_order" is specified, on interactive UI a testcase item is
  disabled unless previous ones in the same test suite have run, even
  that testcase is in a parametrization group. Disorded execution can
  be detected at server side and then errored result is marked.
* In interactive mode the report of a multitest will be reset after
  environment is restarted.
* Fix an issue that `ProcessRunnerTest` & `PyTest` & `PyUnit` have no
  "reset env" button on interactive UI.
* Fix an issue that when "reset env" button is inactive, click event
  should be ignored and no action taken.
* Fix an issue that description of Testplan is missing.

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2021-03-17 08:15 UTC, Pyifan requested changes

2021-03-30 09:55 UTC, raoyitao commented on testplan/runnable/interactive/base.py
> +        self.report[test_uid] = test.dry_run().report
for now I cannot know it.

2021-03-30 09:56 UTC, raoyitao commented on testplan/testing/base.py
> +            env_status=ResourceStatus.STOPPED,
Actually, this init value is coded in the base class ``Test``. Seems we don't need to know it the env starts at 1st time or restart.

2021-03-30 09:58 UTC, raoyitao commented on testplan/testing/multitest/base.py
> +                if (test_filter or self.cfg.test_filter).filter(
I removed a line in this function.

``test_filter`` is passed when interactive handler filters testcases, while ``self.cfg.test_filter`` is used as normal

2021-03-30 09:59 UTC, raoyitao commented on testplan/runnable/interactive/base.py
> +                    ) and not self._prev_testcases_finished(
Yes, need refactor.
This check can happen after ``_should_run`` check, then directly return an error message to client, but does not make changes to the current report.

2021-03-31 07:09 UTC, Pyifan submitted a review, later dismissed

2021-03-31 08:34 UTC, Pyifan approved these changes

2021-03-31 08:48 UTC, merged