Add label for grouping test reports.
morganstanley/testplan pull request #600
Opened 2021-03-29 07:06 UTC by yuxuan-ms

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2021-03-29 07:35 UTC, kn-ms submitted a review, later dismissed

2021-03-31 05:42 UTC, Pyifan commented
Please add documentation for new option in Introduction/Command Line

2021-04-01 08:53 UTC, Pyifan requested changes
per Krisztian, it would be good to include this label field in Information pop-up.

2021-04-02 09:11 UTC, Pyifan approved these changes

2021-04-02 09:47 UTC, merged