Add lineno filepath
morganstanley/testplan pull request #690
Opened 2021-08-16 21:31 UTC by tjisanaMS

## Bug / Requirement Description
Clearly and concisely describe the problem.

## Solution description
Describe your code changes in detail for reviewers.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2021-08-17 08:09 UTC, kn-ms commented on tests/conftest.py
> +                Path(caller_frame.filename).name[:5] == 'test_'):
this could be startswith('test_')

2021-09-09 07:28 UTC, yuxuan-ms requested changes

2021-09-09 07:28 UTC, yuxuan-ms commented on testplan/testing/multitest/result.py
`return entry`

2021-09-10 09:07 UTC, kn-ms commented on testplan/testing/multitest/result.py
>      def greater_equal(self, first, second, description=None, category=None):
this missing an assertion decorator

2021-09-16 09:53 UTC, Pyifan approved these changes

2021-09-23 06:31 UTC, kn-ms approved these changes

2021-09-24 09:35 UTC, yuxuan-ms approved these changes

2021-09-24 09:36 UTC, merged