Interactive reloading should support `plan.schedule`
morganstanley/testplan pull request #729
Opened 2021-11-16 10:01 UTC by raoyitao

Interactive reloading should support `plan.schedule`

* Interactive reload has many issues, to be on the safe side, it is
  suggested to directly import packages/modules in the main script.
  This limitation should be removed and any import syntax should be
  freely used, except for `from mod import *` which is not encouraged.
* Multitest instances added by `plan.add` can be properly reloaded
  interactively, in the way of `plan.schedule` and `plan.schedule_all`
  all the instantiated objects should also be able to be reloaded.
* Add functional testcases for each corner case.
* Fix unit test of reloader.
* Update document.

## Checklist:
- [x] Test
- [x] Example (both test_plan.py and .rst)
- [x] Documentation (API)
- [ ] MS info leakage check
- [ ] For new driver: driver index page
- [ ] For new assertion: ui/pdf/std renderers, documentation
- [ ] For new cmdline arg: documentation

2021-11-18 09:23 UTC, Pyifan requested changes

2021-12-06 08:02 UTC, raoyitao commented on testplan/runnable/interactive/reloader.py
> +            ), "Source code of `modulefinder` library has changed !!"
As I known that the library does not change all the time while python version is changing, I'm afraid that one day the library is totally updated, then we can quickly know from this assertion.

2021-12-09 10:33 UTC, Pyifan approved these changes

2021-12-09 10:33 UTC, Pyifan commented on doc/en/interactive.rst
> +the main script for modules to reload - those who have either been modified or
This is not precise, we will look under the directory of the main script and the directories where the tasks are scheduled from.

2021-12-09 10:33 UTC, Pyifan commented on doc/en/interactive.rst
> +  module name but from different paths.
If the modules from which tasks are scheduled have the same name, they won't reload properly.

2021-12-09 10:33 UTC, Pyifan commented on doc/newsfragments/reload_schedule_task_target.change.rst
> +* Remove interactive reload limitation: the scheduled task target should be supported.
Improvement for interactive mode reload feature (link to how reload works): can now pick up changes to the test added by plan.schedule().

2021-12-10 06:41 UTC, Pyifan approved these changes

2021-12-10 06:41 UTC, merged