Make empty result object not to be false in bool context
morganstanley/testplan pull request #747
Opened 2021-12-22 17:10 UTC by nober97

## Bug / Requirement Description
The Result object can be true only if it contains at least one entry in it. However, a user wants the Result object to be true when it is a valid Result object, even without any entry.
## Solution description
The implementation of the built-in bool() method of the Result class provides this functionality.

## Checklist:
- [ ] Test
- [ ] Example (both test_plan.py and .rst)
- [ ] Documentation (API)
- [ ] News fragment present for release notes
- [ ] MS info leakage check

2021-12-30 03:30 UTC, Pyifan requested changes

2021-12-30 03:30 UTC, Pyifan commented on doc/newsfragments/empty_result.feature.rst
> +* Make empty result object not to be false in bool context
Let's add a period in the end.

2021-12-30 08:54 UTC, nober97 commented on doc/newsfragments/empty_result.feature.rst
> +* Make empty result object not to be false in bool context
Solved

2022-01-05 05:51 UTC, Pyifan approved these changes

2022-01-05 05:52 UTC, merged